// <auto-generated />
using System;
using Dflat.EFCore.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dflat.EFCore.DB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200419165401_Update Mapping")]
    partial class UpdateMapping
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dflat.EFCore.DB.Models.ExcludePath", b =>
                {
                    b.Property<int>("ExcludePathID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FileSourceFolderID")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExcludePathID");

                    b.HasIndex("FileSourceFolderID");

                    b.ToTable("ExcludePaths");
                });

            modelBuilder.Entity("Dflat.EFCore.DB.Models.FileSourceFolder", b =>
                {
                    b.Property<int>("FileSourceFolderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsTemporaryMedia")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastScanStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileSourceFolderID");

                    b.ToTable("FileSourceFolders");
                });

            modelBuilder.Entity("Dflat.EFCore.DB.Models.ExcludePath", b =>
                {
                    b.HasOne("Dflat.EFCore.DB.Models.FileSourceFolder", null)
                        .WithMany("ExcludePaths")
                        .HasForeignKey("FileSourceFolderID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
