// <auto-generated />
namespace Dflat.EF6.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangeIncludeInScanssettingtoIsTemporaryMediainFileSourceFolder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeIncludeInScanssettingtoIsTemporaryMediainFileSourceFolder));
        
        string IMigrationMetadata.Id
        {
            get { return "201904152354289_Change IncludeInScans setting to IsTemporaryMedia in FileSourceFolder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
